name: Run
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3" # Not needed with a `.ruby-version` or `.tool-versions`
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake run
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julien-deramond/update-issue-body@v1
        with:
          issue-number: 1
          body: |
            **Edit**: Some new content
          edit-mode: replace
